[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    spa = "index.html"
