import {MemberData, Rank} from "./modules/member";
import {Template} from "./models/committee";

export const STATE_OPTIONS = [
  { key: 'AL', value: 'AL', text: 'Alabama' },
  { key: 'AK', value: 'AK', text: 'Alaska' },
  { key: 'AZ', value: 'AZ', text: 'Arizona' },
  { key: 'AR', value: 'AR', text: 'Arkansas' },
  { key: 'CA', value: 'CA', text: 'California' },
  { key: 'CO', value: 'CO', text: 'Colorado' },
  { key: 'CT', value: 'CT', text: 'Connecticut' },
  { key: 'DE', value: 'DE', text: 'Delaware' },
  { key: 'DC', value: 'DC', text: 'District Of Columbia' },
  { key: 'FL', value: 'FL', text: 'Florida' },
  { key: 'GA', value: 'GA', text: 'Georgia' },
  { key: 'HI', value: 'HI', text: 'Hawaii' },
  { key: 'ID', value: 'ID', text: 'Idaho' },
  { key: 'IL', value: 'IL', text: 'Illinois' },
  { key: 'IN', value: 'IN', text: 'Indiana' },
  { key: 'IA', value: 'IA', text: 'Iowa' },
  { key: 'KS', value: 'KS', text: 'Kansas' },
  { key: 'KY', value: 'KY', text: 'Kentucky' },
  { key: 'LA', value: 'LA', text: 'Louisiana' },
  { key: 'ME', value: 'ME', text: 'Maine' },
  { key: 'MD', value: 'MD', text: 'Maryland' },
  { key: 'MA', value: 'MA', text: 'Massachusetts' },
  { key: 'MI', value: 'MI', text: 'Michigan' },
  { key: 'MN', value: 'MN', text: 'Minnesota' },
  { key: 'MS', value: 'MS', text: 'Mississippi' },
  { key: 'MO', value: 'MO', text: 'Missouri' },
  { key: 'MT', value: 'MT', text: 'Montana' },
  { key: 'NE', value: 'NE', text: 'Nebraska' },
  { key: 'NV', value: 'NV', text: 'Nevada' },
  { key: 'NH', value: 'NH', text: 'New Hampshire' },
  { key: 'NJ', value: 'NJ', text: 'New Jersey' },
  { key: 'NM', value: 'NM', text: 'New Mexico' },
  { key: 'NY', value: 'NY', text: 'New York' },
  { key: 'NC', value: 'NC', text: 'North Carolina' },
  { key: 'ND', value: 'ND', text: 'North Dakota' },
  { key: 'OH', value: 'OH', text: 'Ohio' },
  { key: 'OK', value: 'OK', text: 'Oklahoma' },
  { key: 'OR', value: 'OR', text: 'Oregon' },
  { key: 'PA', value: 'PA', text: 'Pennsylvania' },
  { key: 'RI', value: 'RI', text: 'Rhode Island' },
  { key: 'SC', value: 'SC', text: 'South Carolina' },
  { key: 'SD', value: 'SD', text: 'South Dakota' },
  { key: 'TN', value: 'TN', text: 'Tennessee' },
  { key: 'TX', value: 'TX', text: 'Texas' },
  { key: 'UT', value: 'UT', text: 'Utah' },
  { key: 'VT', value: 'VT', text: 'Vermont' },
  { key: 'VA', value: 'VA', text: 'Virginia' },
  { key: 'WA', value: 'WA', text: 'Washington' },
  { key: 'WV', value: 'WV', text: 'West Virginia' },
  { key: 'WI', value: 'WI', text: 'Wisconsin' },
  { key: 'WY', value: 'WY', text: 'Wyoming' },
];

export const LANGUAGE_OPTIONS = [
  { key: 'Arabic', text: 'Arabic', value: 'Arabic' },
  { key: 'Chinese', text: 'Chinese', value: 'Chinese' },
  { key: 'Danish', text: 'Danish', value: 'Danish' },
  { key: 'Dutch', text: 'Dutch', value: 'Dutch' },
  { key: 'English', text: 'English', value: 'English' },
  { key: 'French', text: 'French', value: 'French' },
  { key: 'German', text: 'German', value: 'German' },
  { key: 'Greek', text: 'Greek', value: 'Greek' },
  { key: 'Hungarian', text: 'Hungarian', value: 'Hungarian' },
  { key: 'Italian', text: 'Italian', value: 'Italian' },
  { key: 'Japanese', text: 'Japanese', value: 'Japanese' },
  { key: 'Korean', text: 'Korean', value: 'Korean' },
  { key: 'Lithuanian', text: 'Lithuanian', value: 'Lithuanian' },
  { key: 'Persian', text: 'Persian', value: 'Persian' },
  { key: 'Polish', text: 'Polish', value: 'Polish' },
  { key: 'Portuguese', text: 'Portuguese', value: 'Portuguese' },
  { key: 'Russian', text: 'Russian', value: 'Russian' },
  { key: 'Spanish', text: 'Spanish', value: 'Spanish' },
  { key: 'Swedish', text: 'Swedish', value: 'Swedish' },
  { key: 'Turkish', text: 'Turkish', value: 'Turkish' },
  { key: 'Vietnamese', text: 'Vietnamese', value: 'Vietnamese' },
];

export const TAG_OPTIONS = [
  {
    key: 'Important',
    text: 'Important',
    value: 'Important',
    label: { color: 'red', empty: true, circular: true },
  },
  {
    key: 'Announcement',
    text: 'Announcement',
    value: 'Announcement',
    label: { color: 'blue', empty: true, circular: true },
  },
  {
    key: 'Cannot Fix',
    text: 'Cannot Fix',
    value: 'Cannot Fix',
    label: { color: 'black', empty: true, circular: true },
  },
  {
    key: 'News',
    text: 'News',
    value: 'News',
    label: { color: 'purple', empty: true, circular: true },
  },
  {
    key: 'Enhancement',
    text: 'Enhancement',
    value: 'Enhancement',
    label: { color: 'orange', empty: true, circular: true },
  },
  {
    key: 'Change Declined',
    text: 'Change Declined',
    value: 'Change Declined',
    label: { empty: true, circular: true },
  },
  {
    key: 'Off Topic',
    text: 'Off Topic',
    value: 'Off Topic',
    label: { color: 'yellow', empty: true, circular: true },
  },
  {
    key: 'Interesting',
    text: 'Interesting',
    value: 'Interesting',
    label: { color: 'pink', empty: true, circular: true },
  },
  {
    key: 'Discussion',
    text: 'Discussion',
    value: 'Discussion',
    label: { color: 'green', empty: true, circular: true },
  },
];

export type FlagNames = 
  'ad' | 'andorra' | 'ae' | 'united arab emirates' | 'uae' | 'af' | 'afghanistan' | 'ag' | 'antigua' | 'ai' |
  'anguilla' | 'al' | 'albania' | 'am' | 'armenia' | 'an' | 'netherlands antilles' | 'ao' | 'angola' | 'ar' |
  'argentina' | 'as' | 'american samoa' | 'at' | 'austria' | 'au' | 'australia' | 'aw' | 'aruba' | 'ax' |
  'aland islands' | 'az' | 'azerbaijan' | 'ba' | 'bosnia' | 'bb' | 'barbados' | 'bd' | 'bangladesh' | 'be' |
  'belgium' | 'bf' | 'burkina faso' | 'bg' | 'bulgaria' | 'bh' | 'bahrain' | 'bi' | 'burundi' | 'bj' | 'benin' |
  'bm' | 'bermuda' | 'bn' | 'brunei' | 'bo' | 'bolivia' | 'br' | 'brazil' | 'bs' | 'bahamas' | 'bt' | 'bhutan' |
  'bv' | 'bouvet island' | 'bw' | 'botswana' | 'by' | 'belarus' | 'bz' | 'belize' | 'ca' | 'canada' | 'cc' |
  'cocos islands' | 'cd' | 'congo' | 'cf' | 'central african republic' | 'cg' | 'congo brazzaville' | 'ch' |
  'switzerland' | 'ci' | 'cote divoire' | 'ck' | 'cook islands' | 'cl' | 'chile' | 'cm' | 'cameroon' | 'cn' |
  'china' | 'co' | 'colombia' | 'cr' | 'costa rica' | 'cs' | 'cu' | 'cuba' | 'cv' | 'cape verde' | 'cx' |
  'christmas island' | 'cy' | 'cyprus' | 'cz' | 'czech republic' | 'de' | 'germany' | 'dj' | 'djibouti' | 'dk' |
  'denmark' | 'dm' | 'dominica' | 'do' | 'dominican republic' | 'dz' | 'algeria' | 'ec' | 'ecuador' | 'ee' |
  'estonia' | 'eg' | 'egypt' | 'eh' | 'western sahara' | 'er' | 'eritrea' | 'es' | 'spain' | 'et' | 'ethiopia' |
  'eu' | 'european union' | 'fi' | 'finland' | 'fj' | 'fiji' | 'fk' | 'falkland islands' | 'fm' | 'micronesia' |
  'fo' | 'faroe islands' | 'fr' | 'france' | 'ga' | 'gabon' | 'gb' | 'united kingdom' | 'gd' | 'grenada' | 'ge' |
  'georgia' | 'gf' | 'french guiana' | 'gh' | 'ghana' | 'gi' | 'gibraltar' | 'gl' | 'greenland' | 'gm' | 'gambia' |
  'gn' | 'guinea' | 'gp' | 'guadeloupe' | 'gq' | 'equatorial guinea' | 'gr' | 'greece' | 'gs' | 'sandwich islands' |
  'gt' | 'guatemala' | 'gu' | 'guam' | 'gw' | 'guinea-bissau' | 'gy' | 'guyana' | 'hk' | 'hong kong' | 'hm' |
  'heard island' | 'hn' | 'honduras' | 'hr' | 'croatia' | 'ht' | 'haiti' | 'hu' | 'hungary' | 'id' | 'indonesia' |
  'ie' | 'ireland' | 'il' | 'israel' | 'in' | 'india' | 'io' | 'indian ocean territory' | 'iq' | 'iraq' | 'ir' |
  'iran' | 'is' | 'iceland' | 'it' | 'italy' | 'jm' | 'jamaica' | 'jo' | 'jordan' | 'jp' | 'japan' | 'ke' | 'kenya' |
  'kg' | 'kyrgyzstan' | 'kh' | 'cambodia' | 'ki' | 'kiribati' | 'km' | 'comoros' | 'kn' | 'saint kitts and nevis' |
  'kp' | 'north korea' | 'kr' | 'south korea' | 'kw' | 'kuwait' | 'ky' | 'cayman islands' | 'kz' | 'kazakhstan' |
  'la' | 'laos' | 'lb' | 'lebanon' | 'lc' | 'saint lucia' | 'li' | 'liechtenstein' | 'lk' | 'sri lanka' | 'lr' |
  'liberia' | 'ls' | 'lesotho' | 'lt' | 'lithuania' | 'lu' | 'luxembourg' | 'lv' | 'latvia' | 'ly' | 'libya' | 'ma' |
  'morocco' | 'mc' | 'monaco' | 'md' | 'moldova' | 'me' | 'montenegro' | 'mg' | 'madagascar' | 'mh' |
  'marshall islands' | 'mk' | 'macedonia' | 'ml' | 'mali' | 'mm' | 'myanmar' | 'burma' | 'mn' | 'mongolia' | 'mo' |
  'macau' | 'mp' | 'northern mariana islands' | 'mq' | 'martinique' | 'mr' | 'mauritania' | 'ms' | 'montserrat' |
  'mt' | 'malta' | 'mu' | 'mauritius' | 'mv' | 'maldives' | 'mw' | 'malawi' | 'mx' | 'mexico' | 'my' | 'malaysia' |
  'mz' | 'mozambique' | 'na' | 'namibia' | 'nc' | 'new caledonia' | 'ne' | 'niger' | 'nf' | 'norfolk island' | 'ng' |
  'nigeria' | 'ni' | 'nicaragua' | 'nl' | 'netherlands' | 'no' | 'norway' | 'np' | 'nepal' | 'nr' | 'nauru' |
  'nu' | 'niue' | 'nz' | 'new zealand' | 'om' | 'oman' | 'pa' | 'panama' | 'pe' | 'peru' | 'pf' | 'french polynesia' |
  'pg' | 'new guinea' | 'ph' | 'philippines' | 'pk' | 'pakistan' | 'pl' | 'poland' | 'pm' | 'saint pierre' | 'pn' |
  'pitcairn islands' | 'pr' | 'puerto rico' | 'ps' | 'palestine' | 'pt' | 'portugal' | 'pw' | 'palau' | 'py' |
  'paraguay' | 'qa' | 'qatar' | 're' | 'reunion' | 'ro' | 'romania' | 'rs' | 'serbia' | 'ru' | 'russia' | 'rw' |
  'rwanda' | 'sa' | 'saudi arabia' | 'sb' | 'solomon islands' | 'sc' | 'seychelles' | 'gb sct' | 'scotland' | 'sd' |
  'sudan' | 'se' | 'sweden' | 'sg' | 'singapore' | 'sh' | 'saint helena' | 'si' | 'slovenia' | 'sj' | 'svalbard' |
  'jan mayen' | 'sk' | 'slovakia' | 'sl' | 'sierra leone' | 'sm' | 'san marino' | 'sn' | 'senegal' | 'so' |
  'somalia' | 'sr' | 'suriname' | 'st' | 'sao tome' | 'sv' | 'el salvador' | 'sy' | 'syria' | 'sz' | 'swaziland' |
  'tc' | 'caicos islands' | 'td' | 'chad' | 'tf' | 'french territories' | 'tg' | 'togo' | 'th' | 'thailand' | 'tj' |
  'tajikistan' | 'tk' | 'tokelau' | 'tl' | 'timorleste' | 'tm' | 'turkmenistan' | 'tn' | 'tunisia' | 'to' | 'tonga' |
  'tr' | 'turkey' | 'tt' | 'trinidad' | 'tv' | 'tuvalu' | 'tw' | 'taiwan' | 'tz' | 'tanzania' | 'ua' | 'ukraine' |
  'ug' | 'uganda' | 'um' | 'us minor islands' | 'us' | 'america' | 'united states' | 'uy' | 'uruguay' | 'uz' |
  'uzbekistan' | 'va' | 'vatican city' | 'vc' | 'saint vincent' | 've' | 'venezuela' | 'vg' |
  'british virgin islands' | 'vi' | 'us virgin islands' | 'vn' | 'vietnam' | 'vu' | 'vanuatu' | 'gb wls' | 'wales' |
  'wf' | 'wallis and futuna' | 'ws' | 'samoa' | 'ye' | 'yemen' | 'yt' | 'mayotte' | 'za' | 'south africa' | 'zm' |
  'zambia' | 'zw' | 'zimbabwe';

interface TemplateMember {
  name: MemberData['name']
  rank?: Rank // not allowed to use members due to import order
}

export const TEMPLATE_TO_MEMBERS: Record<Template, TemplateMember[]> = {
  'African Union': [
    {name: 'Algeria'},
    {name: 'Angola'},
    {name: 'Benin'},
    {name: 'Botswana'},
    {name: 'Burkina Faso'},
    {name: 'Burundi'},
    {name: 'Cameroon'},
    {name: 'Cape Verde'},
    {name: 'Central African Republic'},
    {name: 'Chad'},
    {name: 'Comoros'},
    {name: 'Congo'},
    {name: 'Cote Divoire'},
    {name: 'Djibouti'},
    {name: 'Egypt'},
    {name: 'Equatorial Guinea'},
    {name: 'Eritrea'},
    {name: 'Ethiopia'},
    {name: 'Gabon'},
    {name: 'Ghana'},
    {name: 'Guinea-Bissau'},
    {name: 'Guinea'},
    {name: 'Kenya'},
    {name: 'Lesotho'},
    {name: 'Liberia'},
    {name: 'Libya'},
    {name: 'Madagascar'},
    {name: 'Malawi'},
    {name: 'Mali'},
    {name: 'Mauritania'},
    {name: 'Mauritius'},
    {name: 'Morocco'},
    {name: 'Mozambique'},
    {name: 'Namibia'},
    {name: 'Niger'},
    {name: 'Nigeria'},
    {name: 'Rwanda'},
    {name: 'Sao Tome'},
    {name: 'Senegal'},
    {name: 'Sierra Leone'},
    {name: 'Sudan'},
    {name: 'Tanzania'},
    {name: 'Togo'},
    {name: 'Tunisia'},
    {name: 'Uganda'},
    {name: 'Zambia'},
    {name: 'Zimbabwe'}
  ],
  'Association of Southeast Asian Nations': [
    {name: 'Brunei'},
    {name: 'Cambodia'},
    {name: 'Indonesia'},
    {name: 'Laos'},
    {name: 'Malaysia'},
    {name: 'Myanmar'},
    {name: 'Philippines'},
    {name: 'Singapore'},
    {name: 'Thailand'},
    {name: 'Vietnam'}
  ],
  'BRICS': [
    {name: 'Brazil'},
    {name: 'China'},
    {name: 'India'},
    {name: 'Russia'},
    {name: 'South Africa'}
  ],
  'European Union': [
    {name: 'Austria'},
    {name: 'Belgium'},
    {name: 'Bulgaria'},
    {name: 'Croatia'},
    {name: 'Cyprus'},
    {name: 'Czech Republic'},
    {name: 'Denmark'},
    {name: 'Estonia'},
    {name: 'Finland'},
    {name: 'France'},
    {name: 'Germany'},
    {name: 'Greece'},
    {name: 'Hungary'},
    {name: 'Ireland'},
    {name: 'Italy'},
    {name: 'Latvia'},
    {name: 'Lithuania'},
    {name: 'Luxembourg'},
    {name: 'Malta'},
    {name: 'Netherlands'},
    {name: 'Poland'},
    {name: 'Portugal'},
    {name: 'Romania'},
    {name: 'Slovakia'},
    {name: 'Slovenia'},
    {name: 'Spain'},
    {name: 'Sweden'},
  ],
  'G20': [
    {name: 'Argentina'},
    {name: 'Australia'},
    {name: 'Brazil'},
    {name: 'Canada'},
    {name: 'China'},
    {name: 'European Union'},
    {name: 'France'},
    {name: 'Germany'},
    {name: 'India'},
    {name: 'Indonesia'},
    {name: 'Italy'},
    {name: 'Japan'},
    {name: 'Mexico'},
    {name: 'Russia'},
    {name: 'Saudi Arabia'},
    {name: 'South Africa'},
    {name: 'South Korea'},
    {name: 'Turkey'},
    {name: 'United Kingdom'},
    {name: 'United States'},
  ],
  'North Atlantic Treaty Organization': [
    {name: 'Albania'},
    {name: 'Belgium'},
    {name: 'Bulgaria'},
    {name: 'Canada'},
    {name: 'Croatia'},
    {name: 'Czech Republic'},
    {name: 'Denmark'},
    {name: 'United Kingdom'},
    {name: 'Estonia'},
    {name: 'France'},
    {name: 'Germany'},
    {name: 'Greece'},
    {name: 'Hungary'},
    {name: 'Iceland'},
    {name: 'Italy'},
    {name: 'Latvia'},
    {name: 'Lithuania'},
    {name: 'Luxembourg'},
    {name: 'Macedonia'},
    {name: 'Montenegro'},
    {name: 'Netherlands Antilles'},
    {name: 'Netherlands'},
    {name: 'Norway'},
    {name: 'Poland'},
    {name: 'Portugal'},
    {name: 'Romania'},
    {name: 'Slovakia'},
    {name: 'Slovenia'},
    {name: 'Spain'},
    {name: 'Turkey'},
    {name: 'United Arab Emirates'},
    {name: 'United States'},
  ],
  'UN Security Council': [
    {name: 'Albania'},
    {name: 'Brazil'},
    {name: 'China', rank: Rank.Veto},
    {name: 'France', rank: Rank.Veto},
    {name: 'Gabon'},
    {name: 'Ghana'},
    {name: 'India'},
    {name: 'Ireland'},
    {name: 'Kenya'},
    {name: 'Mexico'},
    {name: 'Norway'},
    {name: 'Russia', rank: Rank.Veto},
    {name: 'United Arab Emirates'},
    {name: 'United Kingdom', rank: Rank.Veto},
    {name: 'United States', rank: Rank.Veto},
  ],
  'WHO Health Board': [
    {name: 'Argentina'},
    {name: 'Australia'},
    {name: 'Austria'},
    {name: 'Bangladesh'},
    {name: 'Botswana'},
    {name: 'Burkina Faso'},
    {name: 'Chile'},
    {name: 'China'},
    {name: 'Colombia'},
    {name: 'Djibouti'},
    {name: 'Finland'},
    {name: 'Gabon'},
    {name: 'Germany'},
    {name: 'Ghana'},
    {name: 'Grenada'},
    {name: 'Guinea-Bissau'},
    {name: 'Guyana'},
    {name: 'India'},
    {name: 'Indonesia'},
    {name: 'Israel'},
    {name: 'Kenya'},
    {name: 'Madagascar'},
    {name: 'Oman'},
    {name: 'United Kingdom'},
    {name: 'Romania'},
    {name: 'Russia'},
    {name: 'Singapore'},
    {name: 'South Korea'},
    {name: 'Sudan'},
    {name: 'Tajikistan'},
    {name: 'Tonga'},
    {name: 'Tunisia'},
    {name: 'United Arab Emirates'},
    {name: 'United States'}
  ],
  'UN Human Rights Council': [
    {name: 'Afghanistan'},
    {name: 'Angola'},
    {name: 'Argentina'},
    {name: 'Australia'},
    {name: 'Austria'},
    {name: 'Bahamas'},
    {name: 'Bahrain'},
    {name: 'Bangladesh'},
    {name: 'Brazil'},
    {name: 'Bulgaria'},
    {name: 'Burkina Faso'},
    {name: 'Cameroon'},
    {name: 'Chile'},
    {name: 'China'},
    {name: 'Congo'},
    {name: 'Croatia'},
    {name: 'Cuba'},
    {name: 'Czech Republic'},
    {name: 'Denmark'},
    {name: 'Egypt'},
    {name: 'United Kingdom'},
    {name: 'Eritrea'},
    {name: 'Fiji'},
    {name: 'Hungary'},
    {name: 'Iceland'},
    {name: 'Iraq'},
    {name: 'Italy'},
    {name: 'Japan'},
    {name: 'Mexico'},
    {name: 'Nepal'},
    {name: 'Nigeria'},
    {name: 'Pakistan'},
    {name: 'Peru'},
    {name: 'Philippines'},
    {name: 'Qatar'},
    {name: 'Rwanda'},
    {name: 'Saudi Arabia'},
    {name: 'Senegal'},
    {name: 'Slovakia'},
    {name: 'Somalia'},
    {name: 'South Africa'},
    {name: 'Spain'},
    {name: 'Togo'},
    {name: 'Tunisia'},
    {name: 'Ukraine'},
    {name: 'United Arab Emirates'},
    {name: 'Uruguay'}
  ],
  'UN Children\'s Fund': [
    {name: 'Bangladesh'},
    {name: 'Benin'},
    {name: 'Brazil'},
    {name: 'Burundi'},
    {name: 'Cameroon'},
    {name: 'Canada'},
    {name: 'China'},
    {name: 'Colombia'},
    {name: 'Cuba'},
    {name: 'Denmark'},
    {name: 'Djibouti'},
    {name: 'United Kingdom'},
    {name: 'Estonia'},
    {name: 'Germany'},
    {name: 'Ghana'},
    {name: 'Ireland'},
    {name: 'Japan'},
    {name: 'Lithuania'},
    {name: 'Mexico'},
    {name: 'Moldova'},
    {name: 'Mongolia'},
    {name: 'Morocco'},
    {name: 'New Zealand'},
    {name: 'Norway'},
    {name: 'Pakistan'},
    {name: 'Paraguay'},
    {name: 'Russia'},
    {name: 'South Korea'},
    {name: 'Spain'},
    {name: 'Sudan'},
    {name: 'Sweden'},
    {name: 'Switzerland'},
    {name: 'Turkmenistan'},
    {name: 'United States'},
    {name: 'Yemen'},
    {name: 'Zimbabwe'}
  ]
}